name: quran_app
description: A mopile appliccation to view quran.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  quran: ^1.2.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  expandable_page_view: ^1.0.17
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  auto_size_text: ^3.0.0
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  fonts:
    - family: UthmanicHafs_v2-1
      fonts:
        - asset: fonts/UthmanicHafs_v2-1.ttf

